var config = require('./config.js');
var soap = require("soap");
var url = config.url_soap;
var cards = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+DQo8Y2FyZHMtY2F0YWxvZz4NCiAgPGludGVybmFsLWNhcmQgZ3VpZD0iMTAwMCIgbnVtYmVyPSIwMjA5MjAxNSIgZXhwaXJhdGlvbi1kYXRlPSIyMDE3LTAxLTAxIiBzdGF0dXM9IkFDVElWRSIgZGVsZXRlZD0iZmFsc2UiIHBlcmNlbnRhZ2UtZGlzY291bnQ9IjUuMDAiLz4NCiAgPGludGVybmFsLWNhcmQgZ3VpZD0iMjAwMDAiIG51bWJlcj0iMjMyMzIzIiBleHBpcmF0aW9uLWRhdGU9IiIgc3RhdHVzPSJBQ1RJVkUiIGRlbGV0ZWQ9ImZhbHNlIiBwZXJjZW50YWdlLWRpc2NvdW50PSI1LjAwIj4NCiAgICA8Y2xpZW50IGd1aWQ9IjYiIGxhc3QtbmFtZT0i0JLQvtGA0L7QvdC40L0iIGZpcnN0LW5hbWU9ItCc0LjRhdCw0LjQuyIgbWlkZGxlLW5hbWU9ItCQ0L3QtNGA0LXQtdCy0LjRhyIgYmlydGgtZGF0ZT0iMjYuMDkuMTk2MCIgc2V4PSJNQUxFIiBhdXRvPSJmYWxzZSIgY2l0eT0iIiBkaXN0cmljdD0iIiB6aXA9IiIgc3RyZWV0PSIiIGhvdXNlPSIiIGVtYWlsPSIiIG1vYmlsZS1waG9uZT0iIiBwaG9uZT0iIiBwYXMtbnVtYmVyPSIiIHBhcy1zZXJpZT0iIiBkZWxpdmVyeT0iIiBkZWxpdmVyeS1kYXRlPSIiIHNlbmQtYnktc21zPSJ0cnVlIiBzZW5kLWJ5LWVtYWlsPSJ0cnVlIiBkZWxldGVkPSJmYWxzZSIvPg0KICA8L2ludGVybmFsLWNhcmQ+DQogIDxpbnRlcm5hbC1jYXJkIGd1aWQ9IjMwMDAwIiBudW1iZXI9IjMyMzIzMiIgZXhwaXJhdGlvbi1kYXRlPSIiIHN0YXR1cz0iQUNUSVZFIiBkZWxldGVkPSJmYWxzZSIgcGVyY2VudGFnZS1kaXNjb3VudD0iNS4wMCIvPg0KPC9jYXJkcy1jYXRhbG9nPg==";
soap.createClient(url, function(err, client){
	// client.getCardsCatalog(cards, function(err, result){
	// 	console.log(result);
	// })
	console.log(client.describe());
});